import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="no-scrollbar overflow-x-hidden  h-full w-full">
        <div className={"h-full w-full bg-slate-400"}>
          <div>{"Navbar"}</div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
